use UNIVER1

--1
select PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
from FACULTY, PULPIT, PROFESSION
where PULPIT.FACULTY = FACULTY.FACULTY and PROFESSION.FACULTY = FACULTY.FACULTY
	and
	PROFESSION_NAME in (select PROFESSION_NAME 
						from PROFESSION
						where PROFESSION_NAME like '%технологии%' or PROFESSION_NAME like '%технология%');

--2
select PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
from FACULTY inner join PULPIT on FACULTY.FACULTY = PULPIT.FACULTY
			 inner join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY
			 inner join (select PROFESSION_NAME 
						from PROFESSION
						where PROFESSION_NAME like '%технологии%' or PROFESSION_NAME like '%технология%') as Prof on PROFESSION.PROFESSION_NAME = Prof.PROFESSION_NAME;

--3
select PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
from FACULTY inner join PULPIT on FACULTY.FACULTY = PULPIT.FACULTY
			 inner join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY
			 where PROFESSION_NAME like '%технологии%' or PROFESSION_NAME like '%технология%';

--4
select * 
from AUDITORIUM, AUDITORIUM_TYPE 
where AUDITORIUM = (select top(1) AUDITORIUM 
					from AUDITORIUM 
					where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
					order by AUDITORIUM_CAPACITY desc)
ORDER BY AUDITORIUM_CAPACITY DESC;

--5	
select FACULTY.FACULTY_NAME
from FACULTY
where not exists (select * 
				 from PULPIT
				 where FACULTY.FACULTY = PULPIT.FACULTY);

--6
select top 1
(select avg(PROGRESS.NOTE) from PROGRESS
		where PROGRESS.SUBJECT like 'ОАиП')[NOTE],
(select avg(PROGRESS.NOTE) from PROGRESS
		where PROGRESS.SUBJECT like 'БД')[NOTE],
(select avg(PROGRESS.NOTE) from PROGRESS
		where PROGRESS.SUBJECT like 'СУБД')[NOTE]
from PROGRESS

--7
select PROGRESS.IDSTUDENT
from PROGRESS
where PROGRESS.NOTE >=all (select PROGRESS.NOTE
							from PROGRESS
							where PROGRESS.SUBJECT like 'КГ') and PROGRESS.SUBJECT like 'КГ';

--8
select PROGRESS.IDSTUDENT
from PROGRESS
where PROGRESS.NOTE >any (select PROGRESS.NOTE
							from PROGRESS
							where PROGRESS.SUBJECT like 'КГ') and PROGRESS.SUBJECT like 'КГ';