use UNIVER1
--4
BEGIN TRANSACTION;

UPDATE AUDITORIUM
SET AUDITORIUM_NAME = 'первое изменение'
WHERE AUDITORIUM = '236-1';
ROLLBACK;

BEGIN TRANSACTION;
UPDATE AUDITORIUM
SET AUDITORIUM_NAME = 'второе изменение'
WHERE AUDITORIUM = '236-1';
ROLLBACK;

--5
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
UPDATE AUDITORIUM
SET AUDITORIUM_NAME = 'изменено B'
WHERE AUDITORIUM = '236-1';
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY)
VALUES ('9999-91212', 'новая аудитория', 100);
COMMIT;

--6
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
UPDATE AUDITORIUM
SET AUDITORIUM_NAME = 'аудитория'
WHERE AUDITORIUM = '236-1';
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY)
VALUES ('8888-7878', 'фантом', 100);
COMMIT;
rollback;
--7
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
UPDATE AUDITORIUM
SET AUDITORIUM_NAME = 'аудитория'
WHERE AUDITORIUM = '236-1';
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY)
VALUES ('7777-7', 'ййй', 100);
COMMIT;
